edition = "2024";

package cmdproto.v1;

option go_package = "cmdproto.tools/buf-plugin-cmdproto/internal/gen/cmdproto/v1;cmdprotov1";

import "google/protobuf/descriptor.proto";

extend google.protobuf.MethodOptions {
  Command command = 50001;
}

extend google.protobuf.FieldOptions {
  Param param = 50002;
  JsonSchema field_json_schema = 50004;
}

extend google.protobuf.MessageOptions {
  JsonSchema message_json_schema = 50003;
}

message Command {
  string path = 1;
  string summary = 2;
  repeated string alias = 3;
  repeated CliExample example = 4;
  bool hidden = 5;
  bool deprecated = 6;
}

message CliExample {
  string command = 1;
  string description = 2;
  string request_json = 3;
}

message Param {
  Positional positional = 1;
  Flag flag = 2;
  string help = 3;
  bool hidden = 4;
  JsonPayload json = 5;
}

message Positional {
  uint32 index = 1;
}

message Flag {
  string long = 1;
  string short = 2;
}

message JsonPayload {
  bool enabled = 1;
}

message JsonSchema {
  string json = 1;
}
